// <auto-generated />
namespace refactor_me.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createdtheproductstructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createdtheproductstructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201709072326292_Created the product structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
